#!/bin/bash

#Check for xemark executable
if [ -f 'xemark' ];
then
	echo "Found xemark executable, preparing documents"
else
	echo "Could not find xemark executable. Stopping script."
	echo "Please compile xemark and place into path"
fi

#Constants
HEAD="" #Start off with no header
LISTFILES="ls -1 *.xe"
LISTBLOGPOSTS="ls -1 blog/*.xe"
TEMPFILE="tmp.gen"
BLOGFOOTER_OLDER="Older Posts -> page_"
BLOGFOOTER_NEWER="Newer Posts -> page_"
POSTS_PER_PAGE=2
NUM_OF_FILES=$(ls *.xe -1 | wc -l)


#Find the header file if it exists
for file in $LISTFILES; do 
	if [ -f $file ]; then
		if [ $file == "header.xe" ]; then
			HEAD=$file
		fi
	fi
done

#Loop through the xe files and generate html from them
for file in $LISTFILES; do
	if [ -f $file ]; then
		if [ $file == "header.xe" ]; then
			echo "Found header. Skipping"
		else
			#Not reserved, render it
			NEWNAME=${file%.*}
			cat $HEAD $file | ./xemark > "${NEWNAME}.html"
			echo "Creating ${NEWNAME}.html from ${file}"
			if [ -f $HEAD ]; then
				echo "Using header file during generation"
			fi
		fi
	fi
done

#Generate the blog posts with pagination from the blog directory.
COUNTER=1
PAGENUM=1
FILES_TO_JOIN=""

for file in $LISTBLOGPOSTS; do 
	if [ -f $file ]; then
		#Generate the blog
		NEWNAME=${file%.*}
		cat $HEAD $file | ./xemark > "${NEWNAME}.html"
		#Generate the aggregate blog
		FILES_TO_JOIN="${FILES_TO_JOIN} $file "
		if [ $(( COUNTER % POSTS_PER_PAGE )) == $((0)) ]; then
			#If we're at the first page then only the next page should be appended
			if [ $((PAGENUM)) == 1 ]; then
				#need -e for proper escape characters
				echo -e "\n<\n-${BLOGFOOTER_OLDER}$((${PAGENUM}+1))\n>\n" > ${TEMPFILE}
			else
				if [ $(( COUNTER + POSTS_PER_PAGE )) -gt $((NUM_OF_FILES)) ]; then
					echo -e "\n<\n-${BLOGFOOTER_NEWER}$((${PAGENUM}-1))\n>\n" > ${TEMPFILE}	
				else
					echo -e "\n<\n-${BLOGFOOTER_NEWER}$((${PAGENUM}-1))\n-${BLOGFOOTER_OLDER}$((${PAGENUM}+1))\n>\n" > ${TEMPFILE}
				fi
				
			fi
			cat $HEAD $FILES_TO_JOIN $TEMPFILE | ./xemark > "blog/page_${PAGENUM}.html"
			PAGENUM=$((PAGENUM + 1))
			FILES_TO_JOIN=""
		fi
		COUNTER=$((COUNTER+1))
	fi
done

if [ $((COUNTER)) == $((NUM_OF_FILES)) ] && [ $(( $((NUM_OF_FILES)) % $((2)) )) == $((0)) ]; then
	echo -e "\n<\n-${BLOGFOOTER_NEWER}$((${PAGENUM}-1))\n>\n" > ${TEMPFILE}	
	cat $HEAD $FILES_TO_JOIN $TEMPFILE | ./xemark > "blog/page_${PAGENUM}.html"
fi

#Remove the tmp file
rm ${TEMPFILE}

#Finally, if there is a home file, make it the index file
if [ -f "home.html" ]; then
	mv home.html index.html
fi
